exclude: [WP-themeSourceFiles, wordpress.xml, erectlocution.wordpress.2011-09-01.xml, CNAME, bC, bP]
# auto: true
# auto: true --> deprecated
# server: false --> deprecated
markdown: rdiscount
excerpt_seperator: <!--more-->
