#!/bin/bash

# jekyll --server
jekyll

#Replace relative URLs with absolute ones in the feed
sed -f _scripts/absolute_urls.sed _site/feed/index.html > /tmp/atom.xml
mv /tmp/atom.xml _site/feed/index.html
echo "Successfully created RSS feed."
